# Site settings
title: "JUBE"
email: tan.bland@hotmail.fr
description: "Hum, c'est Juste Un Blog Étudiant"
baseurl: ""
url: "http://jube.thaza.eu/"
title_description: "Bienvenu sur JUBE: juste un blog d'étudiant pour partager des informations, des méthodes et des idées sur les sciences et la recherche"
title_image: "https://avatars.githubusercontent.com/u/73999948"
github_repository: https://github.com/jacobtomlinson/carte-noire
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username: Thanakihn
instagram_username: 
reddit_username: 
linkedin_link: 
google_plus_link:
stackoverflow_link:
xing_link:
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> using Jekyll"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/Thanakihn/\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

#GIThub param
lsi: true
safe: true
source: ./
incremental: false
highlighter: rouge
gist:
  noscript: false


# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
